# 101 NumPy Exercises for Data Analysis 

My solutions to the numpy coding challenges at:

https://www.machinelearningplus.com/101-numpy-exercises-python/

In [1]:
# 1. Import numpy as np and see the version

import numpy as np
np.__version__

'1.14.0'

In [2]:
# 2. Create a 1D array of numbers from 0 to 9

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 3. Create a 3×3 numpy array of all Trues

np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
# 4. Extract all odd numbers from arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [5]:
# 5. Replace all odd numbers in arr with -1

arr[arr % 2 == 1] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [6]:
# 6. Replace all odd numbers in arr with -1 without changing arr

np.where(arr % 2 == 1, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
# 7. Convert a 1D array to a 2D array with 2 rows

arr = np.arange(10)

# Something new I learned:
# Setting to -1 automatically decides the number of cols
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
# 8. Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
# 9. Stack the arrays a and b horizontally.

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [10]:
# 10. Q. Create the following pattern without hardcoding.
# Use only numpy functions and the below input array a.

a = np.array([1,2,3])
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [11]:
# 11 Get the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

In [12]:
# 12. From array a remove all items present in array b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])